rules:
  indentation:
    - 1
    -
      size: 'tab'
  class-name-format:
    - 1
    -
      ignore:
        - .pronamic-pay-status-payment_pending
        - .column-pronamic_subscription_status
        - .column-pronamic_payment_status
  property-sort-order:
    - 1
    -
      order:
        - background
        - background-color
        - background-image
        - border
        - border-top
        - border-top-width
        - border-right
        - border-right-width
        - border-bottom
        - border-bottom-width
        - border-left
        - border-left-width
        - border-radius
        - border-spacing
        - box-shadow
        - content
        - clear
        - color
        - cursor
        - display
        - float
        - font-family
        - font-size
        - font-style
        - font-weight
        - line-height
        - list-style
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - max-width
        - padding
        - outline
        - overflow
        - position
        - top
        - right
        - bottom
        - left
        - speak
        - text-indent
        - width
        - height
