filter:
    excluded_paths:
        - "assets/*"
        - "includes/xmlseclibs/*"

checks:
    php:
        code_rating: true
        duplication: true

coding_style:
    php:
        spaces: 
             within: 
                 brackets: true
                 array_initializer: true
                 grouping: true
                 function_call: true
                 function_declaration: true
                 if: true
                 for: true
                 while: true
                 switch: true
                 catch: true
                 type_cast: false
