language: php

php:
    - 5.2
    - 5.3
    - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.5.1 WP_MULTISITE=0
    - WP_VERSION=3.5.1 WP_MULTISITE=1

before_install:
    - git submodule update --init --recursive

before_script:
    # set up WP install
    - WP_CORE_DIR=/tmp/wordpress/
    - mkdir -p $WP_CORE_DIR
    - wget -nv -O /tmp/wordpress.tar.gz https://github.com/WordPress/WordPress/tarball/$WP_VERSION
    - tar --strip-components=1 -zxmf /tmp/wordpress.tar.gz -C $WP_CORE_DIR
    # set up testing suite
    - export WP_DEVELOP_DIR=/tmp/wordpress-develop/
    - export WP_TESTS_DIR=/tmp/wordpress-develop/tests/phpunit/
    - svn co --ignore-externals --quiet svn co http://develop.svn.wordpress.org/trunk/ $WP_DEVELOP_DIR
    - cd $WP_DEVELOP_DIR
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s:dirname( __FILE__ ) . '/wordpress/':'$WP_CORE_DIR':" wp-tests-config.php
    - sed -i "s/yourdbnamehere/wordpress_test/" wp-tests-config.php
    - sed -i "s/yourusernamehere/root/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    - cd -
    # set up database
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot

script: phpunit
